# Generated by Django 6.0.1 on 2026-02-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
