# Generated by Django 6.0.1 on 2026-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDashboard', '0002_remove_patient_email_remove_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
