# Generated by Django 6.0.1 on 2026-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDashboard', '0004_patient_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='raditech_patient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
