# Generated by Django 6.0.1 on 2026-02-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associateDoctorDashboard', '0002_remove_associatedoctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedoctor',
            name='professional_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='associatedoctor',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='associatedoctor',
            name='id_associate_doctor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
