# Generated by Django 6.0.1 on 2026-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associateDoctorDashboard', '0003_associatedoctor_professional_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedoctor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
