# Generated by Django 6.0.1 on 2026-03-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associateDoctorDashboard', '0004_associatedoctor_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedoctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
