# Generated by Django 6.0.1 on 2026-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associateDoctorDashboard', '0005_associatedoctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedoctor',
            name='professional_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
