# Generated by Django 6.0.1 on 2026-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associateDoctorDashboard', '0006_alter_associatedoctor_professional_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedoctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
