# Generated by Django 6.0.1 on 2026-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associateDoctorDashboard', '0007_associatedoctor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedoctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
