# Generated by Django 6.0.1 on 2026-04-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associateDoctorDashboard', '0008_associatedoctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedoctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
