# Generated by Django 6.0.1 on 2026-01-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistantDashboard', '0001_initial'),
        ('doctorsDashboard', '0001_initial'),
        ('patientsDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'In Progress'), ('COM', 'Completed')], default='PEN', max_length=3)),
                ('about', models.CharField(max_length=200)),
                ('patients_description', models.CharField(max_length=200)),
                ('findings', models.TextField()),
                ('conclusions', models.TextField()),
                ('recommendations', models.TextField()),
                ('password', models.CharField(default='', max_length=18)),
                ('doctor_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsDashboard.reportingdoctor')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id_study', models.AutoField(primary_key=True, serialize=False)),
                ('pacs_url', models.CharField(max_length=100)),
                ('email_sent', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsDashboard.patient')),
                ('id_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.report')),
                ('id_study_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistantDashboard.studyrequest')),
            ],
        ),
    ]
