# Generated by Django 6.0.1 on 2026-01-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='id_study',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.study'),
        ),
    ]
