# Generated by Django 6.0.1 on 2026-01-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_id_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id_study',
        ),
    ]
