# Generated by Django 6.0.1 on 2026-03-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='password',
        ),
    ]
