# Generated by Django 6.0.1 on 2026-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_report_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='accession_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='raditech_visit_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='pacs_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
