"""
Data models for the Core Engine of RadiographXpress.
Defines the `Study` and `Report` tables which are central to the application's domain logic.
"""
from django.template.defaultfilters import default
from django.template.defaultfilters import date
from django.db import models
from datetime import datetime

class Study(models.Model):
    """
    Represents a concrete radiological study, created once an initial StudyRequest 
    has been synced with the external Raditech PACS/RIS system.
    
    Acts as the main junction point between a Patient, the original Request, 
    and the final Medical Report.
    """
    id_study = models.AutoField(primary_key=True)
    
    # URL to the DICOM viewer provided by Raditech (populated asynchronously)
    pacs_url = models.CharField(max_length=500, blank=True, default='')
    
    # Tracks if the final results email was successfully dispatched to the patient
    email_sent = models.BooleanField(default=False)
    
    # The date the study was performed
    date = models.DateField()
    
    # Identifiers returned by the external Raditech integration
    raditech_visit_id = models.CharField(max_length=100, null=True, blank=True)
    accession_number = models.CharField(max_length=100, null=True, blank=True)
    
    # Relationships
    id_study_request = models.ForeignKey('assistantDashboard.StudyRequest', on_delete=models.CASCADE)
    id_report = models.ForeignKey('Report', on_delete=models.CASCADE, null=True, blank=True)
    id_patient = models.ForeignKey('patientsDashboard.Patient', on_delete=models.CASCADE)

class Report(models.Model):
    """
    Represents the medical diagnostic report generated by a Reporting Doctor 
    after analyzing a Study's images.
    
    Tracks the lifecycle of the diagnosis via the `status` string field.
    """
    PENDING = 'PEN'
    IN_PROGRESS = 'PRO'
    COMPLETED = 'COM'
    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (IN_PROGRESS, 'In Progress'),
        (COMPLETED, 'Completed'),
    ]

    id_report = models.AutoField(primary_key=True)
    
    # Lifecycle status: PEN -> PRO -> COM
    status = models.CharField(max_length=3, choices=STATUS_CHOICES, default=PENDING)
    
    # Diagnostic text fields
    about = models.CharField(max_length=200)
    patients_description = models.CharField(max_length=200)
    findings = models.TextField()
    conclusions = models.TextField()
    recommendations = models.TextField()
    
    # Date the report was finalized
    date = models.DateField(default=datetime.now)
    
    # The reporting radiologist who claimed and signed the study
    doctor_in_charge = models.ForeignKey('doctorsDashboard.ReportingDoctor', on_delete=models.CASCADE)