# Generated by Django 6.0.1 on 2026-01-29 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientsDashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id_assistant', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id_solicitud_estudio', models.IntegerField(primary_key=True, serialize=False)),
                ('email_doctor', models.EmailField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('requested_study', models.CharField(max_length=100)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsDashboard.patient')),
            ],
        ),
    ]
