# Generated by Django 6.0.1 on 2026-02-03 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantDashboard', '0001_initial'),
        ('associateDoctorDashboard', '0002_remove_associatedoctor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studyrequest',
            name='email_doctor',
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='id_associate_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associateDoctorDashboard.associatedoctor'),
        ),
    ]
