# Generated by Django 6.0.1 on 2026-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantDashboard', '0002_remove_assistant_email_remove_assistant_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
