# Generated by Django 6.0.1 on 2026-03-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantDashboard', '0003_studyrequest_pdf_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='id_solicitud_estudio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
