# Generated by Django 6.0.1 on 2026-03-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantDashboard', '0004_studyrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='first_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
