# Generated by Django 6.0.1 on 2026-03-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantDashboard', '0005_studyrequest_first_printed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='requested_study',
            field=models.CharField(choices=[('Rayos X', [('Torax PA', 'Torax PA'), ('Torax PA y lat', 'Torax PA y lat'), ('Abdomen de cúbito', 'Abdomen de cúbito'), ('Abdomen de pie', 'Abdomen de pie'), ('Cráneo Ap y lat', 'Cráneo Ap y lat'), ('Senos Paranasales 3', 'Senos Paranasales 3'), ('Columna Ap y lat', 'Columna Ap y lat'), ('Huesos', 'Huesos'), ('Otros', 'Otros'), ('Uretrografía Retrógrada', 'Uretrografía Retrógrada'), ('Fistulografía', 'Fistulografía'), ('Tránsito Intestinal', 'Tránsito Intestinal'), ('Urografía Excretora', 'Urografía Excretora'), ('Cistograma (Simple / Transmiccional)', 'Cistograma (Simple / Transmiccional)'), ('Cistouretrografía', 'Cistouretrografía'), ('Colangiografía', 'Colangiografía'), ('Colangiografía en T', 'Colangiografía en T'), ('Histerosalpingografía', 'Histerosalpingografía')]), ('Mastografía', [('Mamografía', 'Mamografía'), ('Mamografía y US Mamas', 'Mamografía y US Mamas')]), ('Procedimientos', [('Marcaje de Mama', 'Marcaje de Mama'), ('Biopsia de Mama', 'Biopsia de Mama'), ('Biopsia de Próstata', 'Biopsia de Próstata'), ('Baaf de tiroides', 'Baaf de tiroides')]), ('Ultrasonido', [('Hígado y Vías Biliares (Boyden)', 'Hígado y Vías Biliares (Boyden)'), ('Abdomen Superior', 'Abdomen Superior'), ('Renal', 'Renal'), ('Pelvis', 'Pelvis'), ('Vesical y próstata', 'Vesical y próstata'), ('Abdomen Completo', 'Abdomen Completo'), ('Mama Doppler', 'Mama Doppler'), ('Obstétrico Doppler', 'Obstétrico Doppler'), ('Obstétrico 4D', 'Obstétrico 4D'), ('Obstétrico Morfológico', 'Obstétrico Morfológico'), ('Endovaginal', 'Endovaginal'), ('Transrectal de Próstata', 'Transrectal de Próstata'), ('Doppler vascular Periférico', 'Doppler vascular Periférico')]), ('Doppler', [('Tiroides', 'Tiroides'), ('Cuello', 'Cuello'), ('Carótidas', 'Carótidas'), ('Transfontanelar', 'Transfontanelar'), ('Mamas', 'Mamas'), ('Testicular', 'Testicular'), ('Musculoesquelético', 'Musculoesquelético'), ('Otros', 'Otros')]), ('Tomografía Computada', [('Cráneo (Simple / Contraste IV)', 'Cráneo (Simple / Contraste IV)'), ('Cuello (Simple / Contraste IV)', 'Cuello (Simple / Contraste IV)'), ('Torax (Simple / Contraste IV)', 'Torax (Simple / Contraste IV)'), ('Abdomen y Pelvis (Simple / Contraste IV / Contraste Oral / Trifásica (hígado))', 'Abdomen y Pelvis (Simple / Contraste IV / Contraste Oral / Trifásica (hígado))'), ('Urotomografía (fase eliminación)', 'Urotomografía (fase eliminación)'), ('Senos Paranasales', 'Senos Paranasales'), ('Hueso Reconstrucción 3D', 'Hueso Reconstrucción 3D'), ('AngioTac', 'AngioTac'), ('Columna', 'Columna'), ('Otro', 'Otro')]), ('Densitometría Ósea', [('Densitometría Ósea', 'Densitometría Ósea')]), ('Estudios Especiales', [('Estudios Especiales', 'Estudios Especiales')])], max_length=100),
        ),
    ]
