# Generated by Django 6.0.1 on 2026-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantDashboard', '0006_alter_studyrequest_requested_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
