# Generated by Django 6.0.1 on 2026-04-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantDashboard', '0007_assistant_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
