# Generated by Django 6.0.1 on 2026-01-26 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedDoctor',
            fields=[
                ('id_associated_doctor', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingDoctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('professional_id', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('associated_doctors', models.ManyToManyField(related_name='patients', to='doctorsDashboard.associateddoctor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.CharField(max_length=200)),
                ('patients_description', models.CharField(max_length=200)),
                ('findings', models.CharField(max_length=2000)),
                ('conclusions', models.CharField(max_length=500)),
                ('recommendations', models.CharField(max_length=500)),
                ('doctor_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsDashboard.reportingdoctor')),
            ],
        ),
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id_solicitud_estudio', models.IntegerField(primary_key=True, serialize=False)),
                ('email_doctor', models.EmailField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('requested_study', models.CharField(max_length=100)),
                ('id_associated_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsDashboard.associateddoctor')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id_study', models.AutoField(primary_key=True, serialize=False)),
                ('pacs_url', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('email_sent', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsDashboard.patient')),
                ('id_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsDashboard.report')),
                ('id_study_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsDashboard.studyrequest')),
            ],
        ),
    ]
