# Generated by Django 6.0.1 on 2026-01-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='id_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorsDashboard.report'),
        ),
    ]
