# Generated by Django 6.0.1 on 2026-01-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0002_alter_study_id_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'In Progress'), ('COM', 'Completed')], default='PEN', max_length=3),
        ),
    ]
