# Generated by Django 6.0.1 on 2026-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0002_remove_reportingdoctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingdoctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='reportingdoctor',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
