# Generated by Django 6.0.1 on 2026-01-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0003_alter_study_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='conclusions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='findings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='recommendations',
            field=models.TextField(),
        ),
    ]
