# Generated by Django 6.0.1 on 2026-03-17 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0003_reportingdoctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdoctor',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
