# Generated by Django 6.0.1 on 2026-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0004_alter_report_conclusions_alter_report_findings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'In Progress'), ('COM', 'Completed')], default='PEN', max_length=3),
        ),
    ]
