# Generated by Django 6.0.1 on 2026-01-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0006_patient_gender_study_doctor_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingdoctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
