# Generated by Django 6.0.1 on 2026-01-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0007_reportingdoctor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='doctor_in_charge',
        ),
    ]
