# Generated by Django 6.0.1 on 2026-01-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0008_remove_study_doctor_in_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='password',
        ),
        migrations.AddField(
            model_name='report',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
