# Generated by Django 6.0.1 on 2026-01-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsDashboard', '0009_remove_study_password_report_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='password',
            field=models.CharField(default='', max_length=18),
        ),
    ]
